// Generated by CodiumAI

/*
Code Analysis

Objective:
The objective of the setScreenSharingActive function is to create an action object that sets the screen sharing status to either active or inactive.

Inputs:
- active: a boolean value that indicates whether screen sharing is active or not.

Flow:
- The function takes in the active boolean value as input.
- It then creates an action object with the type CALL_SET_SCREEN_SHARING_ACTIVE and the active value.
- The action object is then returned by the function.

Outputs:
- An action object with the type CALL_SET_SCREEN_SHARING_ACTIVE and the active value.

Additional aspects:
- This function is a part of a larger Redux architecture.
- The action object returned by this function will be dispatched to the Redux store to update the state of the application.
*/

import { CALL_SET_SCREEN_SHARING_ACTIVE, setScreenSharingActive } from './callActions.ts';

describe('setScreenSharingActive_function', () => {
  // Tests that the function returns an object with the correct type and active value when passed a boolean true
  it('test_true_active', () => {
    const result = setScreenSharingActive(true);
    expect(result).toEqual({
      type: CALL_SET_SCREEN_SHARING_ACTIVE,
      active: true
    });
  });

  // Tests that the function returns an object with the correct type and active value when passed a boolean false
  it('test_false_active', () => {
    const result = setScreenSharingActive(false);
    expect(result).toEqual({
      type: CALL_SET_SCREEN_SHARING_ACTIVE,
      active: false
    });
  });

  // Tests that the function returns an object with the correct type and active value when passed a boolean undefined
  it('test_undefined_active', () => {
    const result = setScreenSharingActive(undefined);
    expect(result).toEqual({
      type: CALL_SET_SCREEN_SHARING_ACTIVE,
      active: undefined
    });
  });

  // Tests that the function returns an object with the correct type and active value when passed a boolean null
  it('test_null_active', () => {
    const result = setScreenSharingActive(null);
    expect(result).toEqual({
      type: CALL_SET_SCREEN_SHARING_ACTIVE,
      active: null
    });
  });

  // Tests that the function returns an object with the correct type and active value when passed a boolean true and additional properties
  it('test_additional_properties_true', () => {
    const result = setScreenSharingActive(true);
    expect(result).toEqual({
      type: CALL_SET_SCREEN_SHARING_ACTIVE,
      active: true
    });
    expect(result).toHaveProperty('type');
    expect(result).toHaveProperty('active');
  });

  // Tests that the function returns an object with the correct type and active value when passed a boolean false and additional properties
  it('test_additional_properties_false', () => {
    const result = setScreenSharingActive(false);
    expect(result).toEqual({
      type: CALL_SET_SCREEN_SHARING_ACTIVE,
      active: false
    });
    expect(result).toHaveProperty('type');
    expect(result).toHaveProperty('active');
  });
});
